// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cheebo/go-config (interfaces: Config)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	go_config "github.com/cheebo/go-config"
	gomock "github.com/golang/mock/gomock"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// Bool mocks base method.
func (m *MockConfig) Bool(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bool", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Bool indicates an expected call of Bool.
func (mr *MockConfigMockRecorder) Bool(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bool", reflect.TypeOf((*MockConfig)(nil).Bool), arg0)
}

// Float mocks base method.
func (m *MockConfig) Float(arg0 string) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Float", arg0)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Float indicates an expected call of Float.
func (mr *MockConfigMockRecorder) Float(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Float", reflect.TypeOf((*MockConfig)(nil).Float), arg0)
}

// Get mocks base method.
func (m *MockConfig) Get(arg0 string) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockConfigMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfig)(nil).Get), arg0)
}

// Int mocks base method.
func (m *MockConfig) Int(arg0 string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Int", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Int indicates an expected call of Int.
func (mr *MockConfigMockRecorder) Int(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Int", reflect.TypeOf((*MockConfig)(nil).Int), arg0)
}

// Int32 mocks base method.
func (m *MockConfig) Int32(arg0 string) int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Int32", arg0)
	ret0, _ := ret[0].(int32)
	return ret0
}

// Int32 indicates an expected call of Int32.
func (mr *MockConfigMockRecorder) Int32(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Int32", reflect.TypeOf((*MockConfig)(nil).Int32), arg0)
}

// Int64 mocks base method.
func (m *MockConfig) Int64(arg0 string) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Int64", arg0)
	ret0, _ := ret[0].(int64)
	return ret0
}

// Int64 indicates an expected call of Int64.
func (mr *MockConfigMockRecorder) Int64(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Int64", reflect.TypeOf((*MockConfig)(nil).Int64), arg0)
}

// Int8 mocks base method.
func (m *MockConfig) Int8(arg0 string) int8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Int8", arg0)
	ret0, _ := ret[0].(int8)
	return ret0
}

// Int8 indicates an expected call of Int8.
func (mr *MockConfigMockRecorder) Int8(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Int8", reflect.TypeOf((*MockConfig)(nil).Int8), arg0)
}

// IsSet mocks base method.
func (m *MockConfig) IsSet(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSet", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSet indicates an expected call of IsSet.
func (mr *MockConfigMockRecorder) IsSet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSet", reflect.TypeOf((*MockConfig)(nil).IsSet), arg0)
}

// SetDefault mocks base method.
func (m *MockConfig) SetDefault(arg0 string, arg1 interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDefault", arg0, arg1)
}

// SetDefault indicates an expected call of SetDefault.
func (mr *MockConfigMockRecorder) SetDefault(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefault", reflect.TypeOf((*MockConfig)(nil).SetDefault), arg0, arg1)
}

// Slice mocks base method.
func (m *MockConfig) Slice(arg0 string) []interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Slice", arg0)
	ret0, _ := ret[0].([]interface{})
	return ret0
}

// Slice indicates an expected call of Slice.
func (mr *MockConfigMockRecorder) Slice(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Slice", reflect.TypeOf((*MockConfig)(nil).Slice), arg0)
}

// SliceInt mocks base method.
func (m *MockConfig) SliceInt(arg0 string) []int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SliceInt", arg0)
	ret0, _ := ret[0].([]int)
	return ret0
}

// SliceInt indicates an expected call of SliceInt.
func (mr *MockConfigMockRecorder) SliceInt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SliceInt", reflect.TypeOf((*MockConfig)(nil).SliceInt), arg0)
}

// SliceString mocks base method.
func (m *MockConfig) SliceString(arg0 string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SliceString", arg0)
	ret0, _ := ret[0].([]string)
	return ret0
}

// SliceString indicates an expected call of SliceString.
func (mr *MockConfigMockRecorder) SliceString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SliceString", reflect.TypeOf((*MockConfig)(nil).SliceString), arg0)
}

// String mocks base method.
func (m *MockConfig) String(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockConfigMockRecorder) String(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockConfig)(nil).String), arg0)
}

// StringMap mocks base method.
func (m *MockConfig) StringMap(arg0 string) map[string]interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringMap", arg0)
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// StringMap indicates an expected call of StringMap.
func (mr *MockConfigMockRecorder) StringMap(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringMap", reflect.TypeOf((*MockConfig)(nil).StringMap), arg0)
}

// StringMapInt mocks base method.
func (m *MockConfig) StringMapInt(arg0 string) map[string]int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringMapInt", arg0)
	ret0, _ := ret[0].(map[string]int)
	return ret0
}

// StringMapInt indicates an expected call of StringMapInt.
func (mr *MockConfigMockRecorder) StringMapInt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringMapInt", reflect.TypeOf((*MockConfig)(nil).StringMapInt), arg0)
}

// StringMapSliceString mocks base method.
func (m *MockConfig) StringMapSliceString(arg0 string) map[string][]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringMapSliceString", arg0)
	ret0, _ := ret[0].(map[string][]string)
	return ret0
}

// StringMapSliceString indicates an expected call of StringMapSliceString.
func (mr *MockConfigMockRecorder) StringMapSliceString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringMapSliceString", reflect.TypeOf((*MockConfig)(nil).StringMapSliceString), arg0)
}

// StringMapString mocks base method.
func (m *MockConfig) StringMapString(arg0 string) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringMapString", arg0)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// StringMapString indicates an expected call of StringMapString.
func (mr *MockConfigMockRecorder) StringMapString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringMapString", reflect.TypeOf((*MockConfig)(nil).StringMapString), arg0)
}

// Sub mocks base method.
func (m *MockConfig) Sub(arg0 string) go_config.Fields {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sub", arg0)
	ret0, _ := ret[0].(go_config.Fields)
	return ret0
}

// Sub indicates an expected call of Sub.
func (mr *MockConfigMockRecorder) Sub(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sub", reflect.TypeOf((*MockConfig)(nil).Sub), arg0)
}

// UInt mocks base method.
func (m *MockConfig) UInt(arg0 string) uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UInt", arg0)
	ret0, _ := ret[0].(uint)
	return ret0
}

// UInt indicates an expected call of UInt.
func (mr *MockConfigMockRecorder) UInt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UInt", reflect.TypeOf((*MockConfig)(nil).UInt), arg0)
}

// UInt32 mocks base method.
func (m *MockConfig) UInt32(arg0 string) uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UInt32", arg0)
	ret0, _ := ret[0].(uint32)
	return ret0
}

// UInt32 indicates an expected call of UInt32.
func (mr *MockConfigMockRecorder) UInt32(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UInt32", reflect.TypeOf((*MockConfig)(nil).UInt32), arg0)
}

// UInt64 mocks base method.
func (m *MockConfig) UInt64(arg0 string) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UInt64", arg0)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// UInt64 indicates an expected call of UInt64.
func (mr *MockConfigMockRecorder) UInt64(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UInt64", reflect.TypeOf((*MockConfig)(nil).UInt64), arg0)
}

// Unmarshal mocks base method.
func (m *MockConfig) Unmarshal(arg0 interface{}, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockConfigMockRecorder) Unmarshal(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockConfig)(nil).Unmarshal), arg0, arg1)
}

// UseSource mocks base method.
func (m *MockConfig) UseSource(arg0 ...go_config.Source) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "UseSource", varargs...)
}

// UseSource indicates an expected call of UseSource.
func (mr *MockConfigMockRecorder) UseSource(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseSource", reflect.TypeOf((*MockConfig)(nil).UseSource), arg0...)
}
